sonar.projectKey=HospitalManagementSystem
sonar.projectName=HospitalManagementSystem
sonar.projectVersion=1.0
sonar.sources=src
sonar.language=java
sonar.java.binaries=.
sonar.host.url=http://localhost:9000
sonar.login=sqp_4ab389c93b293662187c5b93625358215f421c43
